### ISSUE TITLE
Issue's ive found so far

### ISSUE THREAD

**Issue by BlaineP126** [mrgreaper/Phoenix-Titan#1]
[Class's]
Archer - Skills have no Description

[Border Town]
Teleport NPC - Doesn't work
Clothes NPC - Missing
Weapon NPC - Missing
Potion NPC - Missing

[Bichon]
Teleport NPC - Doesn't work
Clothes Shop - Quest - 156 - thats all the information on that - Cannot exit the shop
Potion NPC - Missing
Trainer NPC - Missing

[Monsters]

[Caves]
Bichon - Natural Cave - Bone Elite is on 1st floor, it should be on 3rd floor

[Locations]
Bichon to Woomyon Woods, Cant go through... Map:n0 X:326 Y:36

**Comment by mrgreaper** [comment]
Not sure what you mean by missing npc?
some may be in buildings if you mean the town should have one but does not. 
Or do you mean they are missing text when clicked?

**Comment by BlaineP126** [comment]
In Border village, there's normally a weapons NPC and Clothes NPC but
they're not there, I can log on tomorrow and give you the coords of where
they need to go?

**Comment by mrgreaper** [comment]
Are you sure they are not inside a building? If not make an issue for them
with the cords and we can nudge Andy in that direction :p

**Comment by mrgreaper** [comment]
he should be here : 
![image](https://user-images.githubusercontent.com/2314200/95022344-9ae80c00-066e-11eb-9b46-ae93b12de3ab.png)

my guess is those coords puts him somewhere that he can not exist...should be a simple case of just changing the cords once we know what they are

**Comment by mrgreaper** [comment]
since these are moved to separate issues I am going to close this one
