### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by Sepicu** [mrgreaper/Phoenix-Titan#13]
Any of the resolution options the game will not launch in full screen i just end up with a black panel in the top corner on my desktop.

**Comment by mrgreaper** [comment]
Have a check of the config file and make sure full screen is set to full.
Failing that, could be a resolution or directx problem.
Routinely use full screen myself.

**Comment by mrgreaper** [comment]
Best place to ask for help fixing that issue is: https://www.lomcn.org/forum/forums/crystalm2-help.663/ as its likely something on your pc effecting it rather than a bug with our code. 
Just re-tested to be sure none of the changes we have made are at fault and all seems fine.
