### ISSUE TITLE
Text to speech issue

### ISSUE THREAD

**Issue by Ginge24** [mrgreaper/Phoenix-Titan#14]
So I was farming deer for meat to sell to the butcher, Once I started farming the dead deer the speech system kicked in and told me nothing was found in the carcass. I have turned off all the speech options and relogged and it still happened.
![Screenshot (55)](https://user-images.githubusercontent.com/72410229/95117040-d0a8f580-073f-11eb-80d2-de37c59ce316.png)

**Comment by mrgreaper** [comment]
Can you check your config file and tell me if any of the speech options
have turned themselves to true?

**Comment by Ginge24** [comment]
They have all turned to true in the config file, but In game it tells me they are all turned off

**Comment by mrgreaper** [comment]
hmmm, in the game can you turn them all on and check the config again? 

I am sure if i had them backwards more would of had the bug, but there is no sound on my testing device at mo so its possible

**Comment by Ginge24** [comment]
With all settings turned on in game, the Config file turns to False

**Comment by mrgreaper** [comment]
ok...i am clearly an idiot and have the ticked graphics set to the unticked graphics...no idea how i missed that lol
will be fixed in the next patch, cheers for the report.

**Comment by mrgreaper** [comment]
fixed in next patch
