### ISSUE TITLE
Starter Quest - Butcher

### ISSUE THREAD

**Issue by Ginge24** [mrgreaper/Phoenix-Titan#15]
Once accepting the butcher's first quest in BP it asks you to collect 5 deer meat.  When harvesting deer you collect venison and not deer meat. I have killed over 25 deers looking for 'deer meat' but I only receive venison. So at the moment it is not possible to complete that quest.

**Comment by mrgreaper** [comment]
"deer meat" is a quest item, so long as you have the quest and kill the quest animals it should have a chance to drop (separate from venison which is a standard item)
The gods of random may of just been unkind (or we may still have a bug with it) more testing is needed on that one

**Comment by Ginge24** [comment]
Okay, I kept going at it and finally got my first deermeat. So it was my impatience. So I'm guessing it doesn't need any more feedback as it is working.
