### ISSUE TITLE
Quest 156 traps you in the shop screen (reported bug)

### ISSUE THREAD

**Issue by mrgreaper** [mrgreaper/Phoenix-Titan#2]
**Describe the bug**
Has been reported that the clothes npc in Bichon traps you on the shop screen

**To Reproduce**
Steps to reproduce the behavior: (guessed from report)
1. Click on clothes npc
2. select quest 156
3. pressing escape or clicking the cross will not close the shop screen

**Expected behavior**
did not expect to be trapped in the screen

**Screenshots**
no screenshots available

**Pastebin link to any logs**
not applicable

**Additional context**
This was taken from a more mixed bug report

**Comment by mrgreaper** [comment]
This comes from #1

**Comment by mrgreaper** [comment]
From @BlaineP126 :
The quest 156, you can complete it there and then, no rewards are given, but you can not exit the clothes shop, you have to teleport to sanctuary
When I first went into the shop, I had no quests and didn't accept quest 156 and I still couldn't get out, I don't think the exits work at all.

So this is a two issues: 
Quest 156 not giving an award (in fact the quest file is blank)
The shop where it takes place does not have a transition point.

**Comment by mrgreaper** [comment]
quest 156 (and 155 157) was blank, they have been removed from the data base... partial fix

**Comment by mrgreaper** [comment]
Was able to leave the drapes store via the second stair way 
![image](https://user-images.githubusercontent.com/2314200/95003397-d33c0b80-05d6-11eb-8ccb-b91436908f0b.png)

Both issues resolved

**Comment by BlaineP126** [comment]
In bichon?

**Comment by mrgreaper** [comment]
Yep, same npc room that used to give quest 156, may only be part of those
stairs that works....may need to add more transition points in
