### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by Ginge24** [mrgreaper/Phoenix-Titan#23]
When you buy an item from the game shop it gets delivered to your mailbox. When you try to retrieve the items within the mail, you are unable to do so. I have tried opening and retriveing the items while in Sanc, inside and outside a safe zone elsewhere.
![Screenshot (64)](https://user-images.githubusercontent.com/72410229/96050086-f5544a00-0e70-11eb-93b6-5e2a35d54354.png)

**Comment by Ginge24** [comment]
I have just figured out that you can collect the items from Mr. Smith in the Sanc, but you are unable to collect it from your mailbox.

**Comment by BlaineP126** [comment]
Go into Bichon, go into the Storage Building, you can Receive your items there

**Comment by mrgreaper** [comment]
Not a bug but a mir2 design. Items must be retireved from a storage vendor (I presume this is to prevent abuse of the mail system in dungeons etc)
