### ISSUE TITLE
So far

### ISSUE THREAD

**Issue by Sepicu** [mrgreaper/Phoenix-Titan#7]
Light radius is nowhere near what it should be, outside or in a cave you are pretty much in a tiny circle of light.

Pathing is horrible, prior you could click a mob and the AI would guide you to it in this you constantly get stuck on a tree or behind a chicken.

Constantly getting merged with mobs your about to attack, by that I mean you both become 1, also have noticed when you click to attack your char seems to automatically go to the top position to attack, so not hitting to the side but moving to the top then hitting.

Drops will be resolved at a later date but getting hardly any potions drop, also weight allowance on your char is very bad you quickly run out and have 1 of 2 options, leave the drops and gain nothing for selling the items or constantly tp to town to sell up, which in itself is another issue as if you goto sanc the only place you can tp back to is border village.

**Comment by mrgreaper** [comment]
since these are moved to separate issues I am going to close this one.
